ALTER TABLE "HomeBanner" ADD COLUMN IF NOT EXISTS "image" TEXT;
ALTER TABLE "HomeBanner" ADD COLUMN IF NOT EXISTS "targetType" TEXT;
ALTER TABLE "HomeBanner" ADD COLUMN IF NOT EXISTS "targetId" TEXT;
